(write "Enter the list with parenthesis")
(write-char #\Return)
(write-char #\Linefeed)
(setq l (read))
(write "Enter the number")
(write-char #\Return)
(write-char #\Linefeed)
(setq n (read))
(defvar i 1)
(loop
  (when (= i n) (return i))
  (setq i (+ i 1))
  (setq l (cdr l))
 )
(write (car l))
